const industryErrorCodes = {

    INVALID_CNPJ_LENGTH_ERROR_CODE: "I_IC_01",
    INVALID_PHONE_LENGTH_ERROR_CODE: "I_IP_02",

    SIGN_IN_WITH_EMAIL_AND_PASSWORD_ERROR_CODE: "I_SE_03",
    CREATE_USER_WITH_EMAIL_AND_PASSWORD_ERROR_CODE: "I_CU_03"
}